"""criar_tabela_simulacoes

Revision ID: 7315266a91c9
Revises: 
Create Date: 2026-10-01 17:06:05.899707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7315266a91c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome_cliente', sa.String(length=255), nullable=False),
    sa.Column('renda_mensal_centavos', sa.BigInteger(), nullable=False),
    sa.Column('valor_solicitado_centavos', sa.BigInteger(), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=False),
    sa.Column('finalidade', sa.String(length=100), nullable=False),
    sa.Column('lgpd_consentimento', sa.Boolean(), nullable=False),
    sa.Column('lgpd_data_aceite', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parecer_ia', sa.Text(), nullable=True),
    sa.Column('analista_id', sa.String(length=100), nullable=True),
    sa.Column('observacao_humana', sa.Text(), nullable=True),
    sa.Column('tokens_gastos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulacoes_cpf'), 'simulacoes', ['cpf'], unique=False)
    op.create_index(op.f('ix_simulacoes_id'), 'simulacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulacoes_id'), table_name='simulacoes')
    op.drop_index(op.f('ix_simulacoes_cpf'), table_name='simulacoes')
    op.drop_table('simulacoes')
    # ### end Alembic commands ###
