from enum import Enum

class SimulacaoStatus(Enum):
    PENDENTE_IA = "PENDENTE_IA"
    APROVADO_IA = "APROVADO_IA"
    REPROVADO_IA = "REPROVADO_IA"
    ANALISE_MANUAL = "ANALISE_MANUAL"
    APROVADO_HUMANO = "APROVADO_HUMANO"
    REJEITADO_HUMANO = "REJEITADO_HUMANO"
